version: '3.7'
services:

  mongodb:
    image: mongo
    networks:
      - review-network

  events:
    build:
      context: .
    entrypoint: "yarn events"
    container_name: "events"
    networks:
      - review-network
    depends_on:
      - mongodb

  github-fetch:
    build:
      context: .
    entrypoint: "yarn github-fetch"
    container_name: "github-fetch"
    networks:
      - review-network
    depends_on:
      - events

  front:
    build:
      context: .
    entrypoint: "yarn front"
    container_name: "front"
    ports:
      - "5000:5000"
    networks:
      - review-network
    depends_on:
      - mongodb

networks:
  review-network:
    driver: bridge
