version: '3.7'
services:

  mongodb:
    image: mongo
    networks:
      - review-network

  events:
    build:
      context: .
      dockerfile: ./events.Dockerfile
    container_name: "events"
    networks:
      - review-network
    depends_on:
      - mongodb

networks:
  review-network:
    driver: bridge
