version: '3.1'
services:
  mongodb:
    build: ./mongodb
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - 27017:27017
