export const slackMap = {
  'dmitry.korobeynikov@gmail.com': '@Dmitry Korobeynikov',
  'Dmitry-Korobeynikov@users.noreply.github.com': '@Dmitry Korobeynikov',
  'hackzilla@mail.ru': '@NikolayBolonin',
  'juicy.igor@gmail.com': '@Igor Sachivka',
  'ok.semonenko@gmail.com': '@Oksana Semonenko',
  'dmitriy.chervan@gmail.com': '@Dmytro Chervan',
  'alebedev@spbfiller.com': '@Alex Lebedev',
  'volodymyr.rudyi@pdffiller.team': '@Volodymyr Rudyi',
  'volodymyr.rudyi@gmail.com': '@Volodymyr Rudyi',
  'rysev-a@yandex.ru': '@Aleksei Rysev',
  'vkurnakov@spbfiller.com': '@Kurnakov',
  'kurasixo@gmail.com': '@Kurnakov',
  'ladyzhenskii@gmail.com': '@ladyzhenskii',
  'rodney.sta@gmail.com': '@sshutov',
  'sshutov@spbfiller.com': '@sshutov',
  'paniuta.andrii@pdffiller.team': '@apaniuta',
  'oleg.iaguzhinskii@gmail.com': '@Oleg Nazarov',
  'pinchv@gmail.com': '@Konstantin Zhdanov',
  'msafronov@spbfiller.com': '@msafronov',
  'vitklesv@gmail.com': '@Vitalij Kolesov',
  'nikita@shelimov.me': '@Shelimov',
  'aberkovsky@biarum.com': '@aberkovsky',
  'aberkovsky@spbfiller.com': '@aberkovsky',
  'shpax1@gmail.com': '@shpax',
  'tnizamov@spbfiller.com': '@SPBfiller/Timur Nizamov',
  'korax@pdffiller.com': '@korax',
  'shramko.web@yahoo.com': '@Serhii Shramko',
  'pi.coderman@gmail.com': '@SPBfiller/Ilya Pavlov',
  'afedorov@spbfiller.com': '@SPBfiller/Aleksandr Fedorov',
  'kolomiets.miroslav@pdffiller.team': '@Miroslav Kolomiets',
  'kpetrov@spbfiller.com': '@Konstantin Petrov',
  '51177852+eleven4y@users.noreply.github.com': '@Konstantin Petrov',
  'kolisnyk.roman@pdffiller.team': '@JSFiller / Roman Kolisnyk',
  'karlashchuk.andriy@pdffiller.team': '@JSFiller/kalashnikov',
  'danyliuk.oleksandr@pdffiller.team': '@JSFiller / Oleksandr Danyliuk',
};

export const githubMap = {
  'dmitry.korobeynikov@gmail.com': '@Dmitry-Korobeynikov',
  'Dmitry-Korobeynikov@users.noreply.github.com': '@Dmitry-Korobeynikov',
  'hackzilla@mail.ru': '@nikolaybolonin',
  'juicy.igor@gmail.com': '@isachivka',
  'ok.semonenko@gmail.com': '@oksemonenko',
  'dmitriy.chervan@gmail.com': '@DimaChervan',
  'alebedev@spbfiller.com': '@axlebedev',
  'volodymyr.rudyi@pdffiller.team': '@VolRud',
  'volodymyr.rudyi@gmail.com': '@VolRud',
  'rysev-a@yandex.ru': '@rysev-a',
  'vkurnakov@spbfiller.com': '@kurasixo',
  'kurasixo@gmail.com': '@kurasixo',
  'ladyzhenskii@gmail.com': '@ladyzhenskii',
  'rodney.sta@gmail.com': '@StepanShutov',
  'sshutov@spbfiller.com': '@StepanShutov',
  'paniuta.andrii@pdffiller.team': '@apaniuta',
  'oleg.iaguzhinskii@gmail.com': '@oleg-nazarov',
  'pinchv@gmail.com': '@kzhdanov ',
  'msafronov@spbfiller.com': '@msafronov',
  'vitklesv@gmail.com': '@Matroskins',
  'nikita@shelimov.me': '@shelimov',
  'aberkovsky@biarum.com': '@aberkovsky',
  'aberkovsky@spbfiller.com': '@aberkovsky',
  'shpax1@gmail.com': '@shpax',
  'tnizamov@spbfiller.com': '@kinsm',
  'korax@pdffiller.com': '@vgaivoronskyi',
  'shramko.web@yahoo.com': '@Shramkoweb',
  'pi.coderman@gmail.com': '@PiCoderman',
  'afedorov@spbfiller.com': '@afedorovjs',
  'kolomiets.miroslav@pdffiller.team': '@miroslav-kolomiets',
  'kpetrov@spbfiller.com': '@eleven4y',
  '51177852+eleven4y@users.noreply.github.com': '@eleven4y',
  'kolisnyk.roman@pdffiller.team': '@romkolisnyk',
  'karlashchuk.andriy@pdffiller.team': '@artemkalashnikov',
  'danyliuk.oleksandr@pdffiller.team': '@danyliukOleksandr',
};
